export const actionTypes = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    TOGGLE_CART: 'TOGGLE_CART',
    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    CLEAR_ITEM: 'CLEAR_ITEM',
    UPDATE_COLLECTIONS: 'UPDATE_COLLECTIONS',
    FETCH_COLLECTIONS_START:'FETCH_COLLECTIONS_START',
    FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
    FETCH_COLLECTIONS_FAILURE: 'FETCH_COLLECTIONS_FAILURE'  
};